name: permission_handler_web
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  permission_handler_platform_interface: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: PermissionHandlerPlugin
        fileName: permission_handler_web.dart
